export const projects = [
  {
    id: 1,
    searchableKey: "/banda-alana-feat-silvanny-sivuca",
    projectName:
      "Banda Alana feat Silvanny Sivuca - Filmagem de Monomito Filmes",
    projectCoverImage: "/thumb-alana.png",
    projectCoverImageAlt:
      "Banda Alana feat Silvanny Sivuca - Filmagem de Monomito Filmes",
    projectCoverImageTitle:
      "Banda Alana feat Silvanny Sivuca - Filmagem de Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/OXO8jL7a2VM?si=ZF_jTMfT7funa_M",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 2,
    searchableKey: "/mauro-ramos-audible",
    projectName: "Mauro Ramos - Audible - Monomito Filmes",
    projectCoverImage: "/thumb-audible.png",
    projectCoverImageAlt: "Mauro Ramos - Audible - Monomito Filmes",
    projectCoverImageTitle: "Mauro Ramos - Audible - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/B1iLd1F9GSQ?si=WoMoQS63NBvmDnx-",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 3,
    searchableKey: "/educbank",
    projectName: "Educbank - Monomito Filmes",
    projectCoverImage: "/thumb-educbank.png",
    projectCoverImageAlt: "Educbank - Monomito Filmes",
    projectCoverImageTitle: "Educbank - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/w0sxmf3pILo?si=mOxR3EsJNpCW3lQ4",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 4,
    searchableKey: "/guarana-antarctica",
    projectName: "Making of Guaraná e Joelma - Monomito Filmes",
    projectCoverImage: "/thumb-guarana.png",
    projectCoverImageAlt: "Making of Guaraná e Joelma - Monomito Filmes",
    projectCoverImageTitle: "Making of Guaraná e Joelma - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/5gFX3P5D_7s?si=fUlbzM97CXzcVxy",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 5,
    searchableKey: "/ifood-decola",
    projectName: "iFood Decola - Monomito Filmes",
    projectCoverImage: "/thumb-ifood.png",
    projectCoverImageAlt: "iFood Decola - Monomito Filmes",
    projectCoverImageTitle: "iFood Decola - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/-4rNorxIfGI?si=6gcagBrveg87om8q",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 6,
    searchableKey: "/sintonia-podpah-na-cptm",
    projectName: "Sintonia + Podpah na CPTM - Monomito Filmes",
    projectCoverImage: "/thumb-sintonia.png",
    projectCoverImageAlt: "Sintonia + Podpah na CPTM - Monomito Filmes",
    projectCoverImageTitle: "Sintonia + Podpah na CPTM - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/KK9f_-Vl6wA?si=zqdq5XYyk8xU5fIv",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 7,
    searchableKey: "/tartarugas-ninjas-paramount-e-load",
    projectName: "Tartarugas Ninjas - Paramount e LOAD - Monimotito Filmes",
    projectCoverImage: "/thumb-tartarugas-ninjas.png",
    projectCoverImageAlt:
      "Tartarugas Ninjas - Paramount e LOAD - Monimotito Filmes",
    projectCoverImageTitle:
      "Tartarugas Ninjas - Paramount e LOAD - Monimotito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/bQ3Pn1TBw5s?si=jfq3Hz-kgnTDJgjP",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 8,
    searchableKey: "/festival-mita-tiktok-2023",
    projectName: "Festival Mita + TikTok 2023 - Monomito Filmes",
    projectCoverImage: "/thumb-tiktok.png",
    projectCoverImageAlt: "Festival Mita + TikTok 2023 - Monomito Filmes",
    projectCoverImageTitle: "Festival Mita + TikTok 2023 - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/xZG3dWwCo0o?si=J6NbTZ918nvmCgTY",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 9,
    searchableKey: "/the-town-tiktok-mix-e-vivo",
    projectName: "The Town - TikTok, Mix e Vivo - Monomito Filmes",
    projectCoverImage: "/foto-nao-encontrada.jpg",
    projectCoverImageAlt: "The Town - TikTok, Mix e Vivo - Monomito Filmes",
    projectCoverImageTitle: "The Town - TikTok, Mix e Vivo - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/yIjI2KyCnjQ?si=7k8UXb4Gv1bakm9_",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 10,
    searchableKey: "/girls-tech-day-paulinia-2023",
    projectName: "Girls Tech Day 2023 Paulinia 2023 - Amazon - Monomito Filmes",
    projectCoverImage: "/foto-nao-encontrada.jpg",
    projectCoverImageAlt:
      "Girls Tech Day 2023 Paulinia 2023 - Amazon - Monomito Filmes",
    projectCoverImageTitle:
      "Girls Tech Day 2023 Paulinia 2023 - Amazon - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/cxnXxCXiI3I?si=mUZ5Cn17Q3unYbls",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 11,
    searchableKey: "/glamazon-aftermovie-2023",
    projectName: "Glamazon 2023 - Aftermovie - Monomito Filmes",
    projectCoverImage: "/foto-nao-encontrada.jpg",
    projectCoverImageAlt: "Glamazon 2023 - Aftermovie - Monomito Filmes",
    projectCoverImageTitle: "Glamazon 2023 - Aftermovie - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/wwECDpnscQs?si=uQ6efLAfKsyVVcV4",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 12,
    searchableKey: "/making-of-premio-led-globo",
    projectName: "Making of Prêmio LED - GLOBO - Monomito Filmes",
    projectCoverImage: "/foto-nao-encontrada.jpg",
    projectCoverImageAlt: "Making of Prêmio LED - GLOBO - Monomito Filmes",
    projectCoverImageTitle: "Making of Prêmio LED - GLOBO - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/PWGGI6odXdo?si=ZAII06KGZGKYqlrS",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 13,
    searchableKey: "/festival-banana-da-terra",
    projectName: "Festival Banana da Terra - Monomito Filmes",
    projectCoverImage: "/foto-nao-encontrada.jpg",
    projectCoverImageAlt: "Festival Banana da Terra - Monomito Filmes",
    projectCoverImageTitle: "Festival Banana da Terra - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/zO9mYMRTK4g?si=4sF7e0kjmRQQLzfz",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
  {
    id: 14,
    searchableKey: "/prancha-de-diamante-2023",
    projectName: "Prancha de Diamante 2023 - Eaê! Cosméticos - Monomito Filmes",
    projectCoverImage: "/foto-nao-encontrada.jpg",
    projectCoverImageAlt:
      "Prancha de Diamante 2023 - Eaê! Cosméticos - Monomito Filmes",
    projectCoverImageTitle:
      "Prancha de Diamante 2023 - Eaê! Cosméticos - Monomito Filmes",
    projectVideoUrl:
      "https://www.youtube.com/embed/VW8jQf6lkkw?si=rW5SBAlEAPIY3To5",
    projectPhotograpyDirection: "Ricardo Camargo",
    projectCEO: "Diretor Executivo",
    projectProductionDirector: "Diretor Executivo",
    projectFocus: "Diretor Executivo",
    projectCameraOperator: "Diretor Executivo",
    projectGaffer: ["Um", "Dois"],
    projectArtDirection: "Lilian Cabral",
    projectProduction: [
      "Maria Jardine",
      "Bianca Landulpho",
      "Camila Campos",
      "Romário Viana",
    ],
    projectCostume: "Patricia Passos",
    projectMakeUp: "Elena Passos",
    projectPictures: [
      "/monomito_imagem_grid_1.jpg",
      "/monomito_imagem_grid_2.jpg",
      "/monomito_imagem_grid_3.jpg",
      "/monomito_imagem_grid_4.jpg",
      "/monomito_imagem_grid_5.jpg",
      "/monomito_imagem_grid_6.jpg",
      "/monomito_imagem_grid_7.jpg",
      "/monomito_imagem_grid_8.jpg",
      "/monomito_imagem_grid_9.jpg",
    ],
  },
];
