export const projects = [
    {
        id: 1,
        searchableKey:"/jotade-feat-poeta-marcio-ricardo",
        artistName: "Evidentemente - Jotad3 feat. Poeta Márcio Ricardo",
        artistCoverImage: "/monomito_imagem_grid_1.jpg",
        artistCoverImageAlt: "Evidentemente - Jotad3 feat. Poeta Márcio Ricardo",
        artistCoverImageTitle: "Evidentemente - Jotad3 feat. Poeta Márcio Ricardo",
        artistVideoUrl: "https://www.youtube.com/embed/ePSf1K_RkN8?autoplay=1&mute=1&disablekb=1&controls=0",
        artistPhotograpyDirection: "Ricardo Camargo",
        artistCEO: "Diretor Executivo",
        artistProductionDirector: "Diretor Executivo",
        artistFocus: "Diretor Executivo",
        artistCameraOperator: "Diretor Executivo",
        artistGaffer: ["Um", "Dois"],
        artistArtDirection: "Lilian Cabral",
        artistProduction: [
            "Maria Jardine",
            "Bianca Landulpho",
            "Camila Campos",
            "Romário Viana",
        ],
        artistCostume: "Patricia Passos",
        artistMakeUp: "Elena Passos",
        artistPictures: [
            "/monomito_imagem_grid_1.jpg",
            "/monomito_imagem_grid_2.jpg",
            "/monomito_imagem_grid_3.jpg",
            "/monomito_imagem_grid_4.jpg",
            "/monomito_imagem_grid_5.jpg",
            "/monomito_imagem_grid_6.jpg",
            "/monomito_imagem_grid_7.jpg",
            "/monomito_imagem_grid_8.jpg",
            "/monomito_imagem_grid_9.jpg",
        ]
    },
    {
        id: 2,
        searchableKey:"/lucas-koka-penteado",
        artistName: "Lucas Koka Penteado | Tarja Preta | prod MONOMITO",
        artistCoverImage: "/monomito_imagem_grid_2.jpg",
        artistCoverImageAlt: "Lucas Koka Penteado | Tarja Preta | prod MONOMITO",
        artistCoverImageTitle: "Lucas Koka Penteado | Tarja Preta | prod MONOMITO",
        artistVideoUrl: "https://www.youtube.com/embed/ePSf1K_RkN8?autoplay=1&mute=1&disablekb=1&controls=0",
        artistPhotograpyDirection: "Ricardo Camargo",
        artistCEO: "Diretor Executivo",
        artistProductionDirector: "Diretor Executivo",
        artistFocus: "Diretor Executivo",
        artistCameraOperator: "Diretor Executivo",
        artistGaffer: ["Um", "Dois"],
        artistArtDirection: "Lilian Cabral",
        artistProduction: [
            "Maria Jardine",
            "Bianca Landulpho",
            "Camila Campos",
            "Romário Viana",
        ],
        artistCostume: "Patricia Passos",
        artistMakeUp: "Elena Passos",
        artistPictures: [
            "/monomito_imagem_grid_1.jpg",
            "/monomito_imagem_grid_2.jpg",
            "/monomito_imagem_grid_3.jpg",
            "/monomito_imagem_grid_4.jpg",
            "/monomito_imagem_grid_5.jpg",
            "/monomito_imagem_grid_6.jpg",
            "/monomito_imagem_grid_7.jpg",
            "/monomito_imagem_grid_8.jpg",
            "/monomito_imagem_grid_9.jpg",
        ]
    },
    {
        id: 3,
        searchableKey:"/khalil-magno",
        artistName: "Khalil Magno - Ana Laura e Roni | Canto Monomito 1#",
        artistCoverImage: "/monomito_imagem_grid_3.jpg",
        artistCoverImageAlt: "Khalil Magno - Ana Laura e Roni | Canto Monomito 1#",
        artistCoverImageTitle: "Khalil Magno - Ana Laura e Roni | Canto Monomito 1#",
        artistVideoUrl: "https://www.youtube.com/embed/ePSf1K_RkN8?autoplay=1&mute=1&disablekb=1&controls=0",
        artistPhotograpyDirection: "Ricardo Camargo",
        artistCEO: "Diretor Executivo",
        artistProductionDirector: "Diretor Executivo",
        artistFocus: "Diretor Executivo",
        artistCameraOperator: "Diretor Executivo",
        artistGaffer: ["Um", "Dois"],
        artistArtDirection: "Lilian Cabral",
        artistProduction: [
            "Maria Jardine",
            "Bianca Landulpho",
            "Camila Campos",
            "Romário Viana",
        ],
        artistCostume: "Patricia Passos",
        artistMakeUp: "Elena Passos",
        artistPictures: [
            "/monomito_imagem_grid_1.jpg",
            "/monomito_imagem_grid_2.jpg",
            "/monomito_imagem_grid_3.jpg",
            "/monomito_imagem_grid_4.jpg",
            "/monomito_imagem_grid_5.jpg",
            "/monomito_imagem_grid_6.jpg",
            "/monomito_imagem_grid_7.jpg",
            "/monomito_imagem_grid_8.jpg",
            "/monomito_imagem_grid_9.jpg",
        ]
    },
    {
        id: 4,
        searchableKey:"/mila-rapper",
        artistName: "Mila Rapper | Tarja Preta | prod MONOMITO",
        artistCoverImage: "/monomito_imagem_grid_4.jpg",
        artistCoverImageAlt: "Mila Rapper | Tarja Preta | prod MONOMITO",
        artistCoverImageTitle: "Mila Rapper | Tarja Preta | prod MONOMITO",
        artistVideoUrl: "https://www.youtube.com/embed/ePSf1K_RkN8?autoplay=1&mute=1&disablekb=1&controls=0",
        artistPhotograpyDirection: "Ricardo Camargo",
        artistCEO: "Diretor Executivo",
        artistProductionDirector: "Diretor Executivo",
        artistFocus: "Diretor Executivo",
        artistCameraOperator: "Diretor Executivo",
        artistGaffer: ["Um", "Dois"],
        artistArtDirection: "Lilian Cabral",
        artistProduction: [
            "Maria Jardine",
            "Bianca Landulpho",
            "Camila Campos",
            "Romário Viana",
        ],
        artistCostume: "Patricia Passos",
        artistMakeUp: "Elena Passos",
        artistPictures: [
            "/monomito_imagem_grid_1.jpg",
            "/monomito_imagem_grid_2.jpg",
            "/monomito_imagem_grid_3.jpg",
            "/monomito_imagem_grid_4.jpg",
            "/monomito_imagem_grid_5.jpg",
            "/monomito_imagem_grid_6.jpg",
            "/monomito_imagem_grid_7.jpg",
            "/monomito_imagem_grid_8.jpg",
            "/monomito_imagem_grid_9.jpg",
        ]
    },
    {
        id: 5,
        searchableKey:"/mente-materia",
        artistName: "NÃO É SÓ ISSO - MENTE MATÉRIA feat KIM - prod Rodrigo Cunha | prod MONOMITO FILMES",
        artistCoverImage: "/monomito_imagem_grid_5.jpg",
        artistCoverImageAlt: "NÃO É SÓ ISSO - MENTE MATÉRIA feat KIM - prod Rodrigo Cunha | prod MONOMITO FILMES",
        artistCoverImageTitle: "NÃO É SÓ ISSO - MENTE MATÉRIA feat KIM - prod Rodrigo Cunha | prod MONOMITO FILMES",
        artistVideoUrl: "https://www.youtube.com/embed/ePSf1K_RkN8?autoplay=1&mute=1&disablekb=1&controls=0",
        artistPhotograpyDirection: "Ricardo Camargo",
        artistCEO: "Diretor Executivo",
        artistProductionDirector: "Diretor Executivo",
        artistFocus: "Diretor Executivo",
        artistCameraOperator: "Diretor Executivo",
        artistGaffer: ["Um", "Dois"],
        artistArtDirection: "Lilian Cabral",
        artistProduction: [
            "Maria Jardine",
            "Bianca Landulpho",
            "Camila Campos",
            "Romário Viana",
        ],
        artistCostume: "Patricia Passos",
        artistMakeUp: "Elena Passos",
        artistPictures: [
            "/monomito_imagem_grid_1.jpg",
            "/monomito_imagem_grid_2.jpg",
            "/monomito_imagem_grid_3.jpg",
            "/monomito_imagem_grid_4.jpg",
            "/monomito_imagem_grid_5.jpg",
            "/monomito_imagem_grid_6.jpg",
            "/monomito_imagem_grid_7.jpg",
            "/monomito_imagem_grid_8.jpg",
            "/monomito_imagem_grid_9.jpg",
        ]
    },
    {
        id: 6,
        searchableKey:"/carolina",
        artistName: "Carolina - CarraraFlow (prod Rodrigo Cunha)",
        artistCoverImage: "/monomito_imagem_grid_6.jpg",
        artistCoverImageAlt: "Carolina - CarraraFlow (prod Rodrigo Cunha)",
        artistCoverImageTitle: "Carolina - CarraraFlow (prod Rodrigo Cunha)",
        artistVideoUrl: "https://www.youtube.com/embed/ePSf1K_RkN8?autoplay=1&mute=1&disablekb=1&controls=0",
        artistPhotograpyDirection: "Ricardo Camargo",
        artistCEO: "Diretor Executivo",
        artistProductionDirector: "Diretor Executivo",
        artistFocus: "Diretor Executivo",
        artistCameraOperator: "Diretor Executivo",
        artistGaffer: ["Um", "Dois"],
        artistArtDirection: "Lilian Cabral",
        artistProduction: [
            "Maria Jardine",
            "Bianca Landulpho",
            "Camila Campos",
            "Romário Viana",
        ],
        artistCostume: "Patricia Passos",
        artistMakeUp: "Elena Passos",
        artistPictures: [
            "/monomito_imagem_grid_1.jpg",
            "/monomito_imagem_grid_2.jpg",
            "/monomito_imagem_grid_3.jpg",
            "/monomito_imagem_grid_4.jpg",
            "/monomito_imagem_grid_5.jpg",
            "/monomito_imagem_grid_6.jpg",
            "/monomito_imagem_grid_7.jpg",
            "/monomito_imagem_grid_8.jpg",
            "/monomito_imagem_grid_9.jpg",
        ]
    },
    {
        id: 7,
        searchableKey:"/bia-ferreira",
        artistName: "BIA FERREIRA | PUT YOUR RECORDS ON | prod MONOMITO",
        artistCoverImage: "/monomito_imagem_grid_7.jpg",
        artistCoverImageAlt: "BIA FERREIRA | PUT YOUR RECORDS ON | prod MONOMITO",
        artistCoverImageTitle: "BIA FERREIRA | PUT YOUR RECORDS ON | prod MONOMITO",
        artistVideoUrl: "https://www.youtube.com/embed/ePSf1K_RkN8?autoplay=1&mute=1&disablekb=1&controls=0",
        artistPhotograpyDirection: "Ricardo Camargo",
        artistCEO: "Diretor Executivo",
        artistProductionDirector: "Diretor Executivo",
        artistFocus: "Diretor Executivo",
        artistCameraOperator: "Diretor Executivo",
        artistGaffer: ["Um", "Dois"],
        artistArtDirection: "Lilian Cabral",
        artistProduction: [
            "Maria Jardine",
            "Bianca Landulpho",
            "Camila Campos",
            "Romário Viana",
        ],
        artistCostume: "Patricia Passos",
        artistMakeUp: "Elena Passos",
        artistPictures: [
            "/monomito_imagem_grid_1.jpg",
            "/monomito_imagem_grid_2.jpg",
            "/monomito_imagem_grid_3.jpg",
            "/monomito_imagem_grid_4.jpg",
            "/monomito_imagem_grid_5.jpg",
            "/monomito_imagem_grid_6.jpg",
            "/monomito_imagem_grid_7.jpg",
            "/monomito_imagem_grid_8.jpg",
            "/monomito_imagem_grid_9.jpg",
        ]
    },
    {
        id: 8,
        searchableKey:"/renato-pessoa",
        artistName: "Renato Pessoa - Voo | Canto Monomito 4#",
        artistCoverImage: "/monomito_imagem_grid_8.jpg",
        artistCoverImageAlt: "Renato Pessoa - Voo | Canto Monomito 4#",
        artistCoverImageTitle: "Renato Pessoa - Voo | Canto Monomito 4#",
        artistVideoUrl: "https://www.youtube.com/embed/ePSf1K_RkN8?autoplay=1&mute=1&disablekb=1&controls=0",
        artistPhotograpyDirection: "Ricardo Camargo",
        artistCEO: "Diretor Executivo",
        artistProductionDirector: "Diretor Executivo",
        artistFocus: "Diretor Executivo",
        artistCameraOperator: "Diretor Executivo",
        artistGaffer: ["Um", "Dois"],
        artistArtDirection: "Lilian Cabral",
        artistProduction: [
            "Maria Jardine",
            "Bianca Landulpho",
            "Camila Campos",
            "Romário Viana",
        ],
        artistCostume: "Patricia Passos",
        artistMakeUp: "Elena Passos",
        artistPictures: [
            "/monomito_imagem_grid_1.jpg",
            "/monomito_imagem_grid_2.jpg",
            "/monomito_imagem_grid_3.jpg",
            "/monomito_imagem_grid_4.jpg",
            "/monomito_imagem_grid_5.jpg",
            "/monomito_imagem_grid_6.jpg",
            "/monomito_imagem_grid_7.jpg",
            "/monomito_imagem_grid_8.jpg",
            "/monomito_imagem_grid_9.jpg",
        ]
    },
    {
        id: 9,
        searchableKey:"/arte-e-cultura-na-kebrada",
        artistName: "Rolê no ACK12 - Arte e Cultura na Kebrada | prod MONOMITO",
        artistCoverImage: "/monomito_imagem_grid_9.jpg",
        artistCoverImageAlt: "Rolê no ACK12 - Arte e Cultura na Kebrada | prod MONOMITO",
        artistCoverImageTitle: "Rolê no ACK12 - Arte e Cultura na Kebrada | prod MONOMITO",
        artistVideoUrl: "https://www.youtube.com/embed/ePSf1K_RkN8?autoplay=1&mute=1&disablekb=1&controls=0",
        artistPhotograpyDirection: "Ricardo Camargo",
        artistCEO: "Diretor Executivo",
        artistProductionDirector: "Diretor Executivo",
        artistFocus: "Diretor Executivo",
        artistCameraOperator: "Diretor Executivo",
        artistGaffer: ["Um", "Dois"],
        artistArtDirection: "Lilian Cabral",
        artistProduction: [
            "Maria Jardine",
            "Bianca Landulpho",
            "Camila Campos",
            "Romário Viana",
        ],
        artistCostume: "Patricia Passos",
        artistMakeUp: "Elena Passos",
        artistPictures: [
            "/monomito_imagem_grid_1.jpg",
            "/monomito_imagem_grid_2.jpg",
            "/monomito_imagem_grid_3.jpg",
            "/monomito_imagem_grid_4.jpg",
            "/monomito_imagem_grid_5.jpg",
            "/monomito_imagem_grid_6.jpg",
            "/monomito_imagem_grid_7.jpg",
            "/monomito_imagem_grid_8.jpg",
            "/monomito_imagem_grid_9.jpg",
        ]
    },
]