name: Deploy Next.js Static

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Build + Export
        run: npm run build

      - name: Listar arquivos (opcional)
        run: ls -R out

      # 1) Deploy apenas dos arquivos de texto / HTML
      - name: Deploy Text Files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          timeout: 180000 # Increased timeout
          server: ftp.monomitofilmes.com.br
          username: monomitofilmes
          password: Huehuebr12
          protocol: ftp
          port: 21
          force: true
          concurrent-uploads: 1 # Reduced uploads to prevent errors
          passive: false # Use active mode
          auto-retry: true # Retry on failure
          server-dir: "/home/monomitofilmes/www/"
          local-dir: "./out/"
          exclude: |
            **/*.png
            **/*.jpg
            **/*.jpeg
            **/*.gif
            **/*.svg
            **/*.mp4
            **/*.mov
            **/.git*
            **/.github*/
            **/node_modules*/
            _next/
            _next/**
            404
            404.html

      # 2) Deploy das imagens (e/ou vídeos)
      - name: Deploy Images
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          timeout: 180000
          server: ftp.monomitofilmes.com.br
          username: monomitofilmes
          password: Huehuebr12
          protocol: ftp
          port: 21
          force: true
          concurrent-uploads: 1
          passive: false
          auto-retry: true
          server-dir: "/home/monomitofilmes/www/"
          local-dir: "./out/"
          exclude: |
            **/*.html
            **/*.txt
            **/*.js
            **/*.json
            **/*.css
            **/.git*
            **/.github*/
            **/node_modules*/
            _next/
            _next/**
            404
            404.html
