name: Deploy contato.html Only

on:
  push:
    branches:
      - main

jobs:
  deploy_contact_html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Build + Export
        run: npm run build

      - name: Criar pasta temporária e mover contato.html
        run: |
          mkdir -p out_temp
          cp ./out/contato.html out_temp/

      - name: Listar arquivos na pasta temporária (debug)
        run: ls -R out_temp

      - name: Testar Conexão FTP no GitHub Actions
        run: |
          curl -v --ftp-pasv -u monomitofilmes:Huehuebr12 ftp://ftp.monomitofilmes.com.br

      - name: Deploy contato.html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          timeout: 300000 # 5 minutos para evitar timeout
          server: ftp.monomitofilmes.com.br
          username: monomitofilmes
          password: Huehuebr12
          protocol: ftps # Alterado de FTP para FTPS
          port: 21
          concurrent-uploads: 1 # Apenas 1 upload por vez
          passive: false # Se falhar, troque para passive: true
          auto-retry: true
          keepalive: true
          disable-verification: false
          server-dir: "/home/monomitofilmes/www/"
          local-dir: "./out_temp/"
