name: Deploy Next.js Static

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build + Export
        run: |
          npm run build

      # (Opcional) Checar se a pasta "out/" existe agora
      - name: List generated files
        run: ls -l out

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.monomitofilmes.com.br
          username: monomitofilmes
          password: Huehuebr12
          server-dir: "/home/monomitofilmes/www/"
          local-dir: "./out/"
          exclude: |
            **/.git*
            **/.github*/
            **/node_modules*/
            _next/
            _next/**
            404
            404.html
