name: Deploy contato.html Only

on:
  push:
    branches:
      - main

jobs:
  deploy_contact_html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Build + Export
        run: npm run build

      - name: Criar pasta temporária e mover contato.html
        run: |
          mkdir -p out_temp
          cp ./out/contato.html out_temp/

      - name: Listar arquivos na pasta temporária (debug)
        run: ls -R out_temp

      - name: Deploy contato.html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          keepalive: true
          timeout: 180000
          server: ftp.monomitofilmes.com.br
          username: monomitofilmes
          password: Huehuebr12
          protocol: ftp
          port: 21
          force: true
          concurrent-uploads: 1
          passive: true
          auto-retry: true
          disable-verification: true
          server-dir: "/home/monomitofilmes/www/"
          local-dir: "./out_temp/"
